version: '3.9'

services:
  db:
    image: 'mysql:latest'
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=game
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - "3333:3306"
    volumes:
      - /data/mysql
  app:
    image: game-image
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /data/spring-boot-app